---
- hosts: all
  pre_tasks:
    - name: Check mandatory variables
      assert:
        that: ({{ item }} is defined) and ({{ item }}|length > 0)
      loop:
        - src_root_dir
        - ssl_full_chain_file
        - ssl_private_key_file
        - nginx_conf_path
        - dest_root_dir
        - docker_hub_username
        - docker_hub_password
        - proxy_server_host
        - proxy_server_user
        - proxy_server_pass
  tasks:
    - name: 'Copy compose file'
      copy:
        src: '{{ src_root_dir }}/docker-compose.yml'
        dest: '/home/{{ ansible_user }}/sahabee/'
    - name: 'Create build directories as a hack to make docker-compose work!'
      file:
        path: /home/{{ ansible_user }}/sahabee/{{ item }}
        state: directory
      loop:
        - 'backend/'
        - 'frontend/'
    - name: 'Create SSL directory'
      become: yes
      file:
        path: /etc/sahabee.ir/ssl-files/
        state: directory
    - name: 'Copy SSL private key'
      become: yes
      copy:
        src: '{{ ssl_private_key_file }}'
        dest: /etc/sahabee.ir/ssl-files/privkey.pem
    - name: 'Copy SSL fullchain'
      become: yes
      copy:
        src: '{{ ssl_full_chain_file }}'
        dest: /etc/sahabee.ir/ssl-files/fullchain.pem
    - name: 'Copy nginx config'
      copy:
        src: '{{ nginx_conf_path }}'
        dest: '{{ dest_root_dir }}/'
    - name: 'Copy .env'
      template:
        src: '.env.j2'
        dest: '{{ dest_root_dir }}/.env'
    - name: 'Login to Docker Hub registry (To extend pull rate limit)'
      community.general.docker_login:
        username: '{{ docker_hub_username }}'
        password: '{{ docker_hub_password }}'
    - name: 'Config docker proxy: create config dir'
      become: yes
      file:
        path: /etc/systemd/system/docker.service.d/ &&
        state: directory
    - name: 'Config docker proxy: Copy config file'
      become: yes
      copy:
        content: |
          [Service]
          Environment="HTTP_PROXY=socks5://127.0.0.1:9000"
        dest: /etc/systemd/system/docker.service.d/http-proxy.conf
    - name: 'Restart Docker'
      become: yes
      shell: systemctl daemon-reload && service docker restart && sleep 3
    - name: 'Start socks proxy'
      shell: nohup sshpass -p {{ proxy_server_pass }} ssh -o StrictHostKeyChecking=no -D 0.0.0.0:9000 -N {{ proxy_server_user }}@{{ proxy_server_host }} & echo $! > /tmp/proxy.pid
    - name: 'Pull images'
      docker_compose:
        project_src: '{{ dest_root_dir }}'
        build: no
        pull: yes
        state: present
    - name: 'Deconfig docker proxy'
      become: yes
      file:
        path: /etc/systemd/system/docker.service.d/http-proxy.conf
        state: absent
    - name: 'Stop socks proxy'
      become: yes
      shell: >
        pid=$(cat /tmp/proxy.pid) &&
        echo "Socks proxy pid: $pid" &&
        kill $pid
    - name: 'Restart Docker'
      become: yes
      shell: systemctl daemon-reload && service docker restart && sleep 3
    - name: 'Stop containers'
      docker_compose:
        project_src: '{{ dest_root_dir }}'
        build: no
        pull: no
        state: absent
    - name: 'Start containers'
      docker_compose:
        project_src: '{{ dest_root_dir }}'
        build: no
        pull: no
        state: present
