---
all:
  vars:
    shecan_dns_1: 185.51.200.2
    shecan_dns_2: 178.22.122.100
    src_root_dir: ../..
    dest_root_dir: '/home/{{ ansible_user }}/sahabee/'
    secret_key:
    nginx_conf_path: '{{ src_root_dir }}/nginx.conf'
    docker_hub_username: emranbm
    docker_hub_password:
    api_url: "https://api.sahabee.ir"
    docker_username:
    docker_password:
    proxy_server_host:
    proxy_server_user:
    proxy_server_pass:
    recaptcha_server_key:
    backup_file_remote_path: '/tmp/backup.json'
    backup_file_local_path: './backup.json'
    ssl_full_chain_file:
    ssl_private_key_file:
    api_version:
    frontend_version:
  children:
    production:
      hosts:
        prod1:
          sudo_pass: '{{ lookup("env", "SERVER_PROD_PASS") }}'
          ansible_host: '{{ lookup("env", "SERVER_PROD_IP") | mandatory }}'
          ansible_user: '{{ lookup("env", "SERVER_PROD_USER") | mandatory }}'
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ProxyCommand="sshpass -p {{ proxy_server_pass }} ssh -o StrictHostKeyChecking=no -W %h:%p {{ proxy_server_user }}@{{ proxy_server_host }}"'
          ansible_sudo_pass: '{{ sudo_pass }}'
          ansible_become_pass: '{{ sudo_pass }}'
          ansible_ssh_pass: '{{ lookup("env", "SERVER_PROD_PASS") | mandatory }}'
    test:
      hosts:
        test1:
          ansible_host: sahabee.ir
          ansible_user: root
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          ansible_sudo_pass: root
          ansible_become_pass: root
          ansible_ssh_pass: root
