---
name: Backup production database
on:
  schedule:
    - cron: "30 23 * * *" # every night 23:30 UTC = 03:00 ASIA/TEHRAN
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  backup-production:
    runs-on: ubuntu-20.04
    container:
      image: spy86/ansible:latest
    steps:
      - uses: actions/checkout@v2
      - working-directory: deployment/ansible/
        run: |
          ansible-playbook backup.yml -i inventory.yml --limit production
          echo "${{ secrets.PRODUCTION_BACKUP_FILE_PASS }}" | openssl enc -in backup.json -aes-256-cbc -pass stdin > backup.json.enc
      - uses: actions/upload-artifact@v2
        with:
          name: production-backup
          path: deployment/ansible/backup.json.enc